FROM node:20-alpine

WORKDIR /frontend

COPY . .

RUN apk update

RUN apk add --no-cache python3 py3-pip make g++

RUN npm install

CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--disable-host-check"]